//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace duta.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int id { get; set; }
        public string name { get; set; }
        public int user_id { get; set; }
        public int contact_id { get; set; }
    
        public virtual user contact_ { get; set; }
        public virtual user contacting_user { get; set; }
    }
}
