//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace duta.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public message()
        {
            this.users = new HashSet<user>();
        }
    
        public int message_id { get; set; }
        public System.DateTime time { get; set; }
        public int author_id { get; set; }
        public string message1 { get; set; }
    
        public virtual user author { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}
