//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace duta.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.others_contacts = new HashSet<contact>();
            this.contacts = new HashSet<contact>();
            this.sent_messages = new HashSet<message>();
            this.messages = new HashSet<message>();
        }
    
        public int user_id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int status { get; set; }
        public string description { get; set; }
        public System.DateTime last_status_update { get; set; }
    
        public virtual ICollection<contact> others_contacts { get; set; }
        public virtual ICollection<contact> contacts { get; set; }
        public virtual ICollection<message> sent_messages { get; set; }
        public virtual ICollection<message> messages { get; set; }
    }
}
